name: Local Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the local runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: powershell -ExecutionPolicy Bypass -File npm install --legacy-peer-deps


      - name: Build React App
        run: npm run build

      - name: Deploy Locally
        run: |
          rm -rf /var/www/html/*
          cp -r build/* /var/www/html/
          echo "Deployment complete!"
