name: Local Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your local runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        shell: cmd  # Force it to run in cmd.exe, not PowerShell

      - name: Build React App
        run: npm run build
        shell: cmd  # Same here

      - name: Deploy Locally (Windows)
        run: |
          Remove-Item -Recurse -Force "C:\inetpub\wwwroot\*"
          Copy-Item -Path "build\*" -Destination "C:\inetpub\wwwroot\" -Recurse -Force
          Write-Output "Deployment complete!"
        shell: powershell
        
